Repository googleapis/nodejs-dlp, pull requests merged in 2019-05, with the labels that each got.

#271 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#272 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#273 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#276 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#277 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#278 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#275 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes, status: blocked

#279 fix: DEADLINE_EXCEEDED no longer treated as idempotent and retried
  src/v2/dlp_service_client_config.json
  synth.metadata
Labels: cla: yes

#281 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v2/dlp_service_client_config.json
  synth.metadata
Labels: cla: yes

#284 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#288 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#290 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v2/dlp_service_client.js
  synth.metadata
Labels: cla: yes

#291 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#292 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#293 feat: auto-generate READMEs, add .repo-metdata.json
  .gitignore
  .readme-partials.yml
  .repo-metadata.json
  README.md
  samples/README.md
  samples/jobs.js
  samples/quickstart.js
  samples/risk.js
  samples/templates.js
  samples/triggers.js
  synth.metadata
Labels: cla: yes

#294 chore: release 1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#295 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#296 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
