Repository googleapis/nodejs-dlp, pull requests merged in 2019-04, with the labels that each got.

#261 feat: add x-goog-request-params header
  src/v2/dlp_service_client.js
  synth.metadata
Labels: :rotating_light:, cla: yes

#263 refactor: update formatting of the proto files
  protos/google/privacy/dlp/v2/dlp.proto
  protos/google/privacy/dlp/v2/storage.proto
  src/v2/dlp_service_client.js
  src/v2/doc/google/privacy/dlp/v2/doc_dlp.js
  synth.metadata
Labels: cla: yes

#262 refactor: use execSync for tests
  samples/package.json
  samples/risk.js
  samples/system-test/deid.test.js
  samples/system-test/inspect.test.js
  samples/system-test/jobs.test.js
  samples/system-test/metadata.test.js
  samples/system-test/quickstart.test.js
  samples/system-test/redact.test.js
  samples/system-test/risk.test.js
  samples/system-test/templates.test.js
  samples/system-test/triggers.test.js
Labels: :rotating_light:, cla: yes

#265 chore(docs): formatting updates
  src/v2/doc/google/protobuf/doc_any.js
  src/v2/doc/google/protobuf/doc_field_mask.js
  src/v2/doc/google/protobuf/doc_timestamp.js
  synth.metadata
Labels: cla: yes

#266 chore: re-order template utils
  src/v2/dlp_service_client.js
  synth.metadata
Labels: automerge, cla: yes

#268 Release @google-cloud/dlp v0.12.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: automerge, autorelease: pending, cla: yes

#269 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes
