Repository googleapis/nodejs-dlp, pull requests merged in 2020-07, with the labels that each got.

#493 docs: update readme sample and gitattributes
  .gitattributes
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#500 test: make redact image comparison less strict
  samples/system-test/redact.test.js
Labels: cla: yes

#499 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#498 build: use bazel build
  synth.metadata
  synth.py
Labels: cla: yes

#503 build: typo in gitattribute, and edit retry code names field
  .gitattributes
  protos/google/privacy/dlp/v2/dlp.proto
  protos/google/privacy/dlp/v2/storage.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v2/dlp_service_client.ts
  src/v2/dlp_service_client_config.json
  synth.metadata
  test/gapic_dlp_service_v2.ts
Labels: cla: yes, context: partial

#505 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#506 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#507 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: cla: yes, context: partial

#511 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#510 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#513 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#514 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#515 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#516 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#517 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#519 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
