Repository googleapis/nodejs-dlp, pull requests merged in 2020-06, with the labels that each got.

#484 test: upstream breaking change broke tests
  samples/risk.js
  samples/system-test/jobs.test.js
  samples/system-test/risk.test.js
Labels: cla: yes

#477 build: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#483 feat: Added sample for deid with string replacement
  samples/deid.js
Labels: cla: yes

#478 docs: fix several broken links in the docs
  protos/google/privacy/dlp/v2/dlp.proto
  protos/google/privacy/dlp/v2/storage.proto
  synth.metadata
Labels: automerge, cla: yes, context: partial

#486 fix: proper fallback option handling
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v2/dlp_service_client.ts
  synth.metadata
  tsconfig.json
Labels: cla: yes, context: partial

#489 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#488 fix(samples): include locations/global in parent field
  samples/deid.js
  samples/inspect.js
  samples/jobs.js
  samples/quickstart.js
  samples/redact.js
  samples/risk.js
  samples/system-test/jobs.test.js
  samples/system-test/templates.test.js
  samples/system-test/triggers.test.js
  samples/templates.js
  samples/triggers.js
Labels: cla: yes
