Repository googleapis/nodejs-dlp, pull requests merged in 2020-10, with the labels that each got.

#542 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#543 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: dlp, automerge: exact, cla: yes, context: full

#547 fix: retrieve job config for risk analysis jobs; docs: clarify timespan config for BigQuery and Datastore.
  protos/google/privacy/dlp/v2/dlp.proto
  protos/google/privacy/dlp/v2/storage.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: dlp, automerge, cla: yes, context: full

#550 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#552 docs: add pattern reognition for running samples
  samples/inspectBigQuery.js
  samples/inspectDatastore.js
  samples/inspectFile.js
  samples/inspectGCSFile.js
  samples/inspectString.js
Labels: cla: yes

#553 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#557 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: automerge, cla: yes, context: full
