Repository googleapis/nodejs-dlp, pull requests merged in 2020-09, with the labels that each got.

#535 test: address nightly flake
  samples/system-test/jobs.test.js
Labels: cla: yes

#538 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full

#533 docs: expand parent field format, and BigQuery sampling options. Also describing which transformations are allowed for ReidentifyContent API calls, and the custom alphabet allowed for format-preserving encryption (FPE)
  protos/google/privacy/dlp/v2/dlp.proto
  protos/google/privacy/dlp/v2/storage.proto
  src/v2/dlp_service_client.ts
  synth.metadata
Labels: api: dlp, cla: yes, context: full

#541 docs: correct the links for parent fields
  protos/google/privacy/dlp/v2/dlp.proto
  src/v2/dlp_service_client.ts
  synth.metadata
Labels: cla: yes, context: partial
